cmsDriver.py step2 \
  --python_filename step2_MINIAOD.py \
  --eventcontent MINIAODSIM \
  --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
  --datatier GEN-SIM-DIGI-RAW-MINIAOD \
  --inputCommands "keep *" \
  --conditions 140X_mcRun4_realistic_v4 \
  --customise_commands "process.MINIAODSIMoutput.outputCommands.append('keep *_*_*_HLT'); process.MINIAODSIMoutput.outputCommands.append('keep *_*_*_SIM');" \
  --step RAW2DIGI,RECO,RECOSIM,PAT \
  --geometry Extended2026D110 \
  --era Phase2C17I13M9 \
  --mc \
  --filein file:FILEIN \
  --fileout FILEOUT \
  -n NUM_EVENTS
