cmsDriver.py step2 \
  --python_filename step2_MINIAOD.py \
  --eventcontent MINIAODSIM \
  --customise SLHCUpgradeSimulations/Configuration/aging.customise_aging_1000 \
  --datatier GEN-SIM-DIGI-RAW-MINIAOD \
  --inputCommands "keep *" \
  --conditions auto:phase2_realistic_T33 \
  --step RAW2DIGI,RECO,RECOSIM,PAT \
  --geometry ExtendedRun4D121 \
  --era Phase2C22I13M9 \
  --mc \
  --filein file:FILEIN \
  --fileout FILEOUT \
  -n NUM_EVENTS
