#!/usr/bin/env python

###########################################################
# Track live progress of running grid scan jobs            #
###########################################################
# Use case:
#   For a cluster of condor jobs submitted via run_hgcalreco_grid_submit.py
#   (one job per grid point, each running a single cmsRun re-reco followed
#   by the efficiency/association calculation), show which stage each job
#   is currently in and how many events it has processed so far,
#   without waiting for the jobs to finish.
#   Only meant for jobs submitted via run_hgcalreco_grid_submit.py: it relies
#   on that script's generated job scripts and working-directory/output-file
#   layout, so it will not give sensible results for jobs from other parts of
#   this repo (e.g. sample-production, or the hyperopt submission script,
#   which runs many trials inside a single job rather than one job per point).
#   Progress is read directly from the small "cmsRun.log"/"efficiency.log" files
#   that tools/hgcalrecotools.py::run_local_evaluation now writes into each job's
#   own (persistent) working directory, so - unlike an earlier version of this
#   script - this works regardless of whether the job is still known to condor:
#   the stage/event columns are available even for jobs that have already left
#   the queue, as long as their working directory still exists.
# Usage:
#   python3 jobprogress.py <cluster_id>
# To find the cluster_id, run 'condor_q' and read off the "ID: ..." batch name.


import os
import re
import sys
import json
import argparse
import subprocess


STATUS_MAP = {
    1: 'idle',
    2: 'running',
    3: 'removed',
    4: 'completed',
    5: 'held',
    6: 'transferring',
    7: 'suspended'
}


def get_jobs(cluster_id):
    '''
    Query condor for all procs belonging to a given cluster id.
    Returns a list of dicts with keys 'proc', 'status', 'cmd', sorted by proc id.
    '''
    cmd = ['condor_q', str(cluster_id), '-json']
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0 or not result.stdout.strip():
        return []
    data = json.loads(result.stdout)
    jobs = [{
        'proc': entry.get('ProcId'),
        'status': entry.get('JobStatus'),
        'cmd': entry.get('Cmd'),
    } for entry in data]
    return sorted(jobs, key=lambda j: j['proc'])


def get_workdir(script_path):
    '''
    Parse a condor job script (as generated by run_hgcalreco_grid_submit.py) to find
    the job's own working directory (the last "cd <dir>" line in the script).
    '''
    workdir = None
    with open(script_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('cd '):
                workdir = line[len('cd '):].strip()
    return workdir


def get_max_events(workdir):
    '''
    Read the requested number of events per job from the job's own context.json.
    Returns None if not found, or -1 if all events in the input file(s) are used.
    '''
    context_file = os.path.join(workdir, 'context.json')
    if not os.path.exists(context_file): return None
    with open(context_file, 'r') as f:
        context = json.load(f)
    return context.get('max_events')


def get_current_stage(workdir):
    '''
    Determine which stage is currently active (or last active) for a job, based on
    which output files already exist in its working directory.
    '''
    if workdir is None or not os.path.isdir(workdir): return 'unknown'
    if os.path.exists(os.path.join(workdir, 'result.json')): return 'done'
    if os.path.exists(os.path.join(workdir, 'efficiency.log')): return 'efficiency calculation'
    if os.path.exists(os.path.join(workdir, 'cmsRun.log')): return 'cmsRun (re-reco)'
    return 'not started'


def get_latest_event(workdir, stage):
    '''
    Fetch the latest processed-event number for a job by reading the log files
    tools/hgcalrecotools.py::run_local_evaluation writes into its working directory.
    - During "cmsRun (re-reco)": read from cmsRun.log ("Begin processing the Nth record...").
    - During "efficiency calculation": read from efficiency.log ("Reading event N...").
    Returns None if the relevant log file does not exist yet or has no matching line.
    '''
    if stage=='cmsRun (re-reco)':
        logfile = os.path.join(workdir, 'cmsRun.log')
        pattern = r'Event (\d+), LumiSection'
    elif stage=='efficiency calculation':
        logfile = os.path.join(workdir, 'efficiency.log')
        pattern = r'Reading event (\d+)'
    else:
        return None
    if not os.path.exists(logfile): return None
    with open(logfile, 'r', errors='ignore') as f:
        text = f.read()
    matches = re.findall(pattern, text)
    if matches: return int(matches[-1])
    return None


if __name__=='__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('cluster_id', type=int,
        help='Condor cluster ID, as shown by condor_q (e.g. the number in "ID: 13202810").')
    args = parser.parse_args()

    jobs = get_jobs(args.cluster_id)
    if len(jobs)==0:
        print(f'No jobs found in the queue for cluster {args.cluster_id}.')
        print('(Note: job status/listing requires the cluster to still be known to condor;')
        print(' the stage/event columns themselves would still work off the working')
        print(' directories alone, see get_current_stage/get_latest_event.)')
        sys.exit()

    header = f'{"job":>4} {"status":>8} {"stage":<22} {"event":>10}'
    print(header)
    print('-'*len(header))
    for job in jobs:
        proc = job['proc']
        status = STATUS_MAP.get(job['status'], str(job['status']))
        stage = '-'
        eventstr = '-'
        if job['cmd'] is not None and os.path.exists(job['cmd']):
            workdir = get_workdir(job['cmd'])
            if workdir is not None and os.path.isdir(workdir):
                stage = get_current_stage(workdir)
                maxevents = get_max_events(workdir)
                event = get_latest_event(workdir, stage)
                if event is not None:
                    totalstr = '?' if (maxevents is None or maxevents<0) else str(maxevents)
                    eventstr = f'{event}/{totalstr}'
        print(f'{proc:>4} {status:>8} {stage:<22} {eventstr:>10}')
