#!/usr/bin/env python

###########################################################
# Track live progress of running grid scan jobs            #
###########################################################
# Use case:
#   For a cluster of condor jobs submitted via run_hgcalreco_grid_submit.py
#   (one job per grid point, each running a single cmsRun re-reco followed
#   by the efficiency/association calculation), show which stage each job
#   is currently in and how many events it has processed so far,
#   without waiting for the jobs to finish.
#   Only meant for jobs submitted via run_hgcalreco_grid_submit.py: it relies
#   on that script's generated job scripts and working-directory/output-file
#   layout, so it will not give sensible results for jobs from other parts of
#   this repo (e.g. sample-production, or the hyperopt submission script,
#   which runs many trials inside a single job rather than one job per point).
#   This only works for jobs still known to condor (i.e. queued, running,
#   or held); once a job leaves the queue, use the regular log files instead
#   (see ../tools/jobcheck.py).
#   Note: unlike sample-production, both cmsRun and the efficiency calculation
#   are run here as subprocesses with capture_output=True (see
#   tools/hgcalrecotools.py::run_local_evaluation), so their stdout/stderr are
#   captured internally rather than streamed to the job's own stdout/stderr.
#   This means the "stage" column below is reliable, but the "event" column
#   will usually show "-" (no live per-event progress available) even while
#   a job is actively running.
# Usage:
#   python3 jobprogress.py <cluster_id>
# To find the cluster_id, run 'condor_q' and read off the "ID: ..." batch name.


import os
import re
import sys
import json
import argparse
import subprocess


STATUS_MAP = {
    1: 'idle',
    2: 'running',
    3: 'removed',
    4: 'completed',
    5: 'held',
    6: 'transferring',
    7: 'suspended'
}


def get_jobs(cluster_id):
    '''
    Query condor for all procs belonging to a given cluster id.
    Returns a list of dicts with keys 'proc', 'status', 'cmd', sorted by proc id.
    '''
    cmd = ['condor_q', str(cluster_id), '-json']
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0 or not result.stdout.strip():
        return []
    data = json.loads(result.stdout)
    jobs = [{
        'proc': entry.get('ProcId'),
        'status': entry.get('JobStatus'),
        'cmd': entry.get('Cmd'),
    } for entry in data]
    return sorted(jobs, key=lambda j: j['proc'])


def get_workdir(script_path):
    '''
    Parse a condor job script (as generated by run_hgcalreco_grid_submit.py) to find
    the job's own working directory (the last "cd <dir>" line in the script).
    '''
    workdir = None
    with open(script_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('cd '):
                workdir = line[len('cd '):].strip()
    return workdir


def get_max_events(workdir):
    '''
    Read the requested number of events per job from the job's own context.json.
    Returns None if not found, or -1 if all events in the input file(s) are used.
    '''
    context_file = os.path.join(workdir, 'context.json')
    if not os.path.exists(context_file): return None
    with open(context_file, 'r') as f:
        context = json.load(f)
    return context.get('max_events')


def get_current_stage(workdir):
    '''
    Determine which stage is currently active for a job, based on which
    output files already exist in its working directory.
    '''
    if workdir is None or not os.path.isdir(workdir): return 'unknown'
    if os.path.exists(os.path.join(workdir, 'result.json')): return 'done'
    if os.path.exists(os.path.join(workdir, 'hgcalreco_out.root')): return 'efficiency calculation'
    if os.path.exists(os.path.join(workdir, 'config.py')): return 'cmsRun (re-reco)'
    return 'not started'


def get_latest_event(cluster_id, proc, stage, maxbytes=2000):
    '''
    Fetch the latest processed-event number for a running job via condor_tail.
    - During "cmsRun (re-reco)": read from stderr ("Begin processing the Nth record...").
    - During "efficiency calculation": read from stdout ("Reading event N...").
    Returns None if condor_tail fails or no matching line is found yet.
    '''
    job_id = f'{cluster_id}.{proc}'
    if stage=='cmsRun (re-reco)':
        cmd = ['condor_tail', '-stderr', '-maxbytes', str(maxbytes), job_id]
        pattern = r'Event (\d+), LumiSection'
    elif stage=='efficiency calculation':
        cmd = ['condor_tail', '-maxbytes', str(maxbytes), job_id]
        pattern = r'Reading event (\d+)'
    else:
        return None
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except subprocess.TimeoutExpired:
        return None
    matches = re.findall(pattern, result.stdout)
    if matches: return int(matches[-1])
    return None


if __name__=='__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('cluster_id', type=int,
        help='Condor cluster ID, as shown by condor_q (e.g. the number in "ID: 13202810").')
    args = parser.parse_args()

    jobs = get_jobs(args.cluster_id)
    if len(jobs)==0:
        print(f'No jobs found in the queue for cluster {args.cluster_id}.')
        print('(Note: this only works for jobs still known to condor; already-completed')
        print(' or removed jobs no longer show up here, use the log files instead.)')
        sys.exit()

    header = f'{"job":>4} {"status":>8} {"stage":<22} {"event":>10}'
    print(header)
    print('-'*len(header))
    for job in jobs:
        proc = job['proc']
        status = STATUS_MAP.get(job['status'], str(job['status']))
        stage = '-'
        eventstr = '-'
        if status=='running' and job['cmd'] is not None and os.path.exists(job['cmd']):
            workdir = get_workdir(job['cmd'])
            stage = get_current_stage(workdir)
            maxevents = get_max_events(workdir) if workdir is not None else None
            event = get_latest_event(args.cluster_id, proc, stage)
            if event is not None:
                totalstr = '?' if (maxevents is None or maxevents<0) else str(maxevents)
                eventstr = f'{event}/{totalstr}'
        print(f'{proc:>4} {status:>8} {stage:<22} {eventstr:>10}')
