#!/usr/bin/env python

###########################################################
# Track live progress of running sample-production jobs   #
###########################################################
# Use case:
#   For a cluster of condor jobs running the sample-production chain
#   (cmsdriver step0/1/2, see produce.py in this same folder),
#   show which step and which event each job is currently processing,
#   without waiting for the jobs to finish.
#   Only meant for jobs submitted via produce.py: it relies on that script's
#   generated job scripts and working-directory/step-file layout, so it will
#   not give sensible results for jobs from other parts of this repo
#   (e.g. run-hgcal-reco, run-hgcal-reco-scan).
#   This only works for jobs still known to condor (i.e. queued, running,
#   or held); once a job leaves the queue, use the regular log files instead
#   (see ../tools/jobcheck.py).
# Usage:
#   python3 jobprogress.py <cluster_id>
# To find the cluster_id, run 'condor_q' and read off the "ID: ..." batch name.


import os
import re
import sys
import json
import argparse
import subprocess


STATUS_MAP = {
    1: 'idle',
    2: 'running',
    3: 'removed',
    4: 'completed',
    5: 'held',
    6: 'transferring',
    7: 'suspended'
}


def get_jobs(cluster_id):
    '''
    Query condor for all procs belonging to a given cluster id.
    Returns a list of dicts with keys 'proc', 'status', 'cmd', sorted by proc id.
    '''
    cmd = ['condor_q', str(cluster_id), '-json']
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0 or not result.stdout.strip():
        return []
    data = json.loads(result.stdout)
    jobs = [{
        'proc': entry.get('ProcId'),
        'status': entry.get('JobStatus'),
        'cmd': entry.get('Cmd'),
    } for entry in data]
    return sorted(jobs, key=lambda j: j['proc'])


def get_workdir_and_nevents(script_path):
    '''
    Parse a condor job script (as generated by produce.py) to find:
    - the job's own working directory (the last "cd <dir>" before any cmsDriver command)
    - the number of events per step (from the "-n <N>" argument to cmsDriver)
    '''
    workdir = None
    nevents = None
    with open(script_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('cd '):
                workdir = line[len('cd '):].strip()
            if line.startswith('cmsDriver.py'):
                if nevents is None:
                    match = re.search(r'-n\s+(\d+)', line)
                    if match: nevents = int(match.group(1))
                break
    return workdir, nevents


def get_current_step(workdir):
    '''
    Determine which cmsDriver step is currently active for a job,
    based on which step*.root output files already exist in its working directory.
    '''
    if workdir is None or not os.path.isdir(workdir): return 'unknown'
    if os.path.exists(os.path.join(workdir, 'step2.root')): return 'step2 (RECO/MiniAOD)'
    if os.path.exists(os.path.join(workdir, 'step1.root')): return 'step1 (DIGI/PU mixing)'
    if os.path.exists(os.path.join(workdir, 'step0.root')): return 'step0 (GEN-SIM)'
    return 'not started'


def get_latest_event(cluster_id, proc, maxbytes=2000):
    '''
    Fetch the latest "Begin processing the Nth record" line from a running
    job's stderr via condor_tail, and extract the event number.
    Returns None if condor_tail fails or no such line is found (e.g. job
    still initializing, or between two events with a lot of other output).
    '''
    job_id = f'{cluster_id}.{proc}'
    cmd = ['condor_tail', '-stderr', '-maxbytes', str(maxbytes), job_id]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except subprocess.TimeoutExpired:
        return None
    matches = re.findall(r'Event (\d+), LumiSection', result.stdout)
    if matches: return int(matches[-1])
    return None


if __name__=='__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('cluster_id', type=int,
        help='Condor cluster ID, as shown by condor_q (e.g. the number in "ID: 13185504").')
    args = parser.parse_args()

    jobs = get_jobs(args.cluster_id)
    if len(jobs)==0:
        print(f'No jobs found in the queue for cluster {args.cluster_id}.')
        print('(Note: this only works for jobs still known to condor; already-completed')
        print(' or removed jobs no longer show up here, use the log files instead.)')
        sys.exit()

    header = f'{"job":>4} {"status":>8} {"step":<22} {"event":>10}'
    print(header)
    print('-'*len(header))
    for job in jobs:
        proc = job['proc']
        status = STATUS_MAP.get(job['status'], str(job['status']))
        step = '-'
        eventstr = '-'
        if status=='running' and job['cmd'] is not None and os.path.exists(job['cmd']):
            workdir, nevents = get_workdir_and_nevents(job['cmd'])
            step = get_current_step(workdir)
            event = get_latest_event(args.cluster_id, proc)
            if event is not None:
                eventstr = f'{event}/{nevents}' if nevents is not None else str(event)
        print(f'{proc:>4} {status:>8} {step:<22} {eventstr:>10}')
